services:
  traci:
    build: TraCI-script
    volumes:
      - ./tmp/data:/app/data
      - ./TraCI-script:/app
    
  controller_master:
    build: Controller
    volumes:
      - ./Controller:/app

  controller_node:
    build: Controller
    volumes:
      - ./Controller:/app
      - /var/run/docker.sock:/var/run/docker.sock