networks:
  deep:
    driver: bridge
  backend:
    driver: bridge

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
    volumes:
      - ./Controller/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - deep
      - backend
    healthcheck:
      test: ["CMD", "mosquitto_pub", "-h", "localhost", "-t", "test", "-m", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: claxon
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  traci:
    image: ghcr.io/c-l-a-x-o-n/traci-script/traci:latest
    depends_on:
      mosquitto:
        condition: service_healthy
      sumo:
        condition: service_started
    environment:
      MQTT_HOST: mosquitto
      MQTT_PORT: 1883
      SUMO_HOST: sumo
      SUMO_PORT: 8873
    networks:
      - deep
    
  controller_master:
    image: ghcr.io/c-l-a-x-o-n/controller/controller:latest
    depends_on:
      controller_node:
        condition: service_started
      mosquitto:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      BROKER_HOST: mosquitto
      BROKER_PORT: 1883
      MASTER: "True"
      DB_HOST: postgres
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: claxon
    ports:
      - "7890:7890"
    networks:
      - backend
      - deep

  controller_node:
    image: ghcr.io/c-l-a-x-o-n/controller/controller:latest
    depends_on:
      mosquitto:
        condition: service_healthy
      traci:
        condition: service_started
    environment:
      BROKER_HOST: mosquitto
      BROKER_PORT: 1883
    networks:
      - backend
      - deep

  sumo_config_gen:
    build: ./TraCI-script
    command: ["python3", "config_gen.py"]
    volumes:
      - traci_config:/app/data
    

  sumo:
    image: ghcr.io/eclipse-sumo/sumo
    command: ["sumo", "-c", "/config/file.sumocfg", "--remote-port", "8873"]
    ports:
      - "8873:8873"
    volumes:  
      - traci_config:/config
    depends_on:
      sumo_config_gen:
        condition: service_completed_successfully
    networks:
      - deep

volumes:
  traci_config:
    driver: local