services:
  traci:
    build: TraCI-script
    volumes:
      - ./TraCI-script:/app
    
  controller_master:
    build: Controller
    volumes:
      - ./Controller:/app

  controller_node:
    build: Controller
    volumes:
      - ./Controller:/app